---
apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    author: tukov
    name: redis-pod
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379
...