---
apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    author: tukov
    name: voting-app-pod
spec:
  containers:
    - name: voting-app
      image: dockersamples/examplevotingapp_vote
      ports:
        - containerPort: 80
...